DEBUG:
  LEVEL: "INFO"
  PARTS:
    MAIN:
      NAME: "donkey.manage"
      LEVEL: "INFO"
    PERFMON:
      NAME: "donkey.perfmon"
      LEVEL: "INFO"
      FILE: "/d2-tmpfs/perfmon.txt"
    PERFDUMP:
      NAME: "donkey.perfdump"
      LEVEL: "INFO"
      TIMEOUT: 30
    TRACER:
      FILE: "/d2-tmpfs/trace.log"
    TXCTRL:
      NAME: "donkey.txctrl"
      LEVEL: "INFO"
    CAMERA:
      NAME: "donkey.camera"
      LEVEL: "INFO"
    ACT-THROTTLE:
      NAME: "donkey.act-throttle"
      LEVEL: "INFO"
    ACT-STEERING:
      NAME: "donkey.act-steering"
      LEVEL: "INFO"
  
MODEL:
  MODEL_IN_USE: 0

CAMERA:
  POSTFIX_SCRIPT: "/home/pi/setCam.sh"


ACTUATOR:
  THROTTLE_FORWARD_PWM: 460
  THROTTLE_STOPPED_PWM: 384
  THROTTLE_REVERSE_PWM: 310
  THROTTLE_KICK_PULSE: 410
  THROTTLE_KICK_LENGTH: 4
  THROTTLE_FULLSPEED_PULSE: 415
  THROTTLE_BRAKE_PULSE: 350
  THROTTLE_MIN_SPD_PULSE: 405
  THROTTLE_CONSTANT_MODE: 1
  FULLSPEED_DECISION_THRESH: 0.8
  FULLSPEED_HYSTERESIS_LENGTH: 3
  BRAKE_DECISION_THRESH: 0.8
  BRAKE_HYSTERESIS_LENGTH: 5
  USE_ARM_LOGIC: 1
  STEERING_RIGHT_FIX: 1.5
  
TX:
  TX_THROTTLE_MIN: 1105
  TX_THROTTLE_MAX: 1910
  TX_STEERING_MIN: 1163
  TX_STEERING_MAX: 1905
  TX_THROTTLE_TRESH: 1470
  TX_CH_AUX_TRESH: 1500
  TX_SPEEDOMETER_MIN: 1000
  TX_SPEEDOMETER_MAX: 8000
  TX_SERIAL: "/dev/ttyS4"

POST_PILOT:
  STEERING_TRIM_RIGHT_THRES: 0.1
  STEERING_TRIM_RIGHT_FACTOR: 1
  STEERING_TRIM_LEFT_THRES: 0.1
  STEERING_TRIM_LEFT_FACTOR: 1

